[workspace]
members = ["tower-sesh", "tower-sesh-*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = []
license = "MIT"
readme = "README.md"
categories = ["asynchronous", "session", "tower"]
keywords = []
edition = "2021"
rust-version = "1.82.0"

[workspace.dependencies]
serde = { version = "1.0.217", default-features = false, features = ["std"] }

[workspace.lints]
