[workspace]
members = [".", "examples/axum"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = []
license = "MIT"
readme = "README.md"
categories = ["asynchronous", "session", "tower"]
keywords = []
edition = "2021"
rust-version = "1.82.0"

[workspace.lints]

[package]
name = "tower-sesh"
description = "Tower middleware for session authentication via cookies"
version.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
categories.workspace = true
keywords.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
async-trait = "0.1.83"
axum = { version = "0.7.9", optional = true }
base64 = "0.22.1"
cookie = { version = "0.18.1", features = ["signed", "private"] }
futures = "0.3.31"
http = "1.2.0"
parking_lot = "0.12.3"
pin-project-lite = "0.2.15"
rand = "0.8.5"
thiserror = "2.0.7"
tower = "0.5.2"
tower-cookies = "0.10.0"
tracing = { version = "0.1.41", optional = true }

[features]
default = ["axum", "tracing"]

[dev-dependencies]
quickcheck = "1.0.3"
tokio = { version = "1.42.0", features = ["full"] }

[lints]
workspace = true
