[package]
name = "example-axum"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = "0.7.9"
tokio = { version = "1.42.0", features = ["full"] }
tower = "0.5.2"
tower-cookies = "0.10.0"
tower-sesh = { path = "../..", features = ["axum"] }
