[package]
name = "tower-sesh"
description = "Tower middleware for session authentication via cookies"
version.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
categories.workspace = true
keywords.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = "1.0.94"
async-trait = "0.1.83"
cookie = { version = "0.18.1", features = [
    "signed",
    "private",
    "percent-encode",
] }
futures = "0.3.31"
http = "1.2.0"
itoa = "1.0.14"
parking_lot = "0.12.3"
pin-project-lite = "0.2.15"
ryu = "1.0.18"
serde = { workspace = true }
time = "0.3.37"
tower = "0.5.2"
tower-sesh-core = { version = "0.1.0", path = "../tower-sesh-core" }

# optional dependencies
axum = { version = "0.7.9", optional = true }
tracing = { version = "0.1.41", optional = true }

[dev-dependencies]
insta = "1.42.0"
quickcheck = "1.0.3"
rmp-serde = "1.3.0"
serde_json = "1.0.136"
tokio = { version = "1.42.0", features = ["full"] }

[features]
default = ["axum", "tracing"]

[lints]
workspace = true
