[package]
name = "benches"
version = "0.0.0"
publish = false
edition = { workspace = true }
license = { workspace = true }

[dependencies]
criterion = "0.5.1"

[[bench]]
name = "record"
path = "record/main.rs"
harness = false
