[package]
name = "benches"
version = "0.0.0"
publish = false
license.workspace = true
edition.workspace = true

[dependencies]
divan = "0.1.17"
tokio = { version = "=1.43.0", features = ["full"] }
tower-sesh = { path = "../tower-sesh" }
tower-sesh-core = { path = "../tower-sesh-core" }

[[bench]]
name = "stores"
path = "stores.rs"
harness = false
