name: Audit

on:
  push:
    branches:
      - main
    paths:
      - "**/Cargo.toml"
      - deny.toml
  schedule:
    - cron: "8 1 * * *" # 1:08AM UTC
  pull_request: {}

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v2
